### ISSUE TITLE
Timer already started

### ISSUE THREAD

**Issue by mrdanbrooks** [osrf/rqt_graphprofiler#11]
```
Traceback (most recent call last):
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 53, in _callback
    self._user_callback()
  File "./host_profiler.py", line 96, in _publish_profile
    node_monitor.start()
  File "./host_profiler.py", line 221, in start
    self.start_time = self._interval_timer.start()
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 30, in start
    return self._start()
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 38, in _start
    raise Exception("Timer already started")
Exception: Timer already started
```

**Comment by mrdanbrooks** [comment]
When doing restart - after cancel() try waiting for is_alive to be false?

**Comment by mrdanbrooks** [comment]
this approach doesn't work. you basically want to do a join() but you can't do that from the thread you are currently on. 

New approach - throw an exception

**Comment by mrdanbrooks** [comment]
Also this is difficult to reproduce.

**Comment by mrdanbrooks** [comment]
```
[ERROR] Exception when starting node monitor '/robot_state_publisher': Timer thread already started.
```

No monitors were created or destroyed around this new exception.

I wonder if it is always the same process? maybe something is getting restarted

**Comment by mrdanbrooks** [comment]
I have left this running for a day now. It seems stable, but is probably being caused by a race condition of some sort. Closing for now.

**Comment by mrdanbrooks** [comment]
+1 /robot_state_publisher ? is there something special about this?
