### ISSUE TITLE
Handling XML RPC errors

### ISSUE THREAD

**Issue by mrdanbrooks** [osrf/rqt_graphprofiler#12]
```
Updating Graph
Adding Monitor for '/test'
WANRING: XML RPC ERROR
Publishing 12 nodes
Publishing Monitors: 12
Subscribing Monitors: 12
Traceback (most recent call last):
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 53, in _callback
    self._user_callback()
  File "./host_profiler.py", line 91, in _publish_profile
    self._publisher.publish(host)
  File "/home/dan/ros_catkin_ws/install_isolated/lib/python2.7/dist-packages/rospy/topics.py", line 823, in publish
    raise ROSSerializationException(str(e))
ROSSerializationException: field nodes[].pid must be an integer type

```

**Comment by mrdanbrooks** [comment]
When this happens, probably the node just doesn't exist? So it should be removed. But also, this will probably keep happening since the master thinks the node is there.

**Comment by mrdanbrooks** [comment]
functionality moved to rosprofiler
