### ISSUE TITLE
node process not being assigned

### ISSUE THREAD

**Issue by mrdanbrooks** [osrf/rqt_graphprofiler#19]
```
Updating Graph
Adding Monitor for '/rostopic_30276_1407282947058'
Publishing 11 nodes
Publishing Monitors: 11
Subscribing Monitors: 11

---
Traceback (most recent call last):
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 53, in _callback
    self._user_callback()
  File "./host_profiler.py", line 294, in _update_callback
    self.cpu_log.append(self._process.get_cpu_percent())
AttributeError: 'NoneType' object has no attribute 'get_cpu_percent'
Publishing 11 nodes
Publishing Monitors: 11
Subscribing Monitors: 11

---
Traceback (most recent call last):
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 53, in _callback
    self._user_callback()
  File "./host_profiler.py", line 294, in _update_callback
    self.cpu_log.append(self._process.get_cpu_percent())
AttributeError: 'NoneType' object has no attribute 'get_cpu_percent'
Publishing 11 nodes
Publishing Monitors: 11
Subscribing Monitors: 11

---
Traceback (most recent call last):
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 53, in _callback
    self._user_callback()
  File "./host_profiler.py", line 294, in _update_callback
    self.cpu_log.append(self._process.get_cpu_percent())
AttributeError: 'NoneType' object has no attribute 'get_cpu_percent'

```

**Comment by mrdanbrooks** [comment]
functionality moved to rosprofiler
