### ISSUE TITLE
Node Monitors occasionally die!

### ISSUE THREAD

**Issue by mrdanbrooks** [osrf/rqt_graphprofiler#22]

**Comment by mrdanbrooks** [comment]
```
Publishing 11 nodes
Publishing Monitors: 11
Subscribing Monitors: 11
---
Updating Graph
Publishing 11 nodes
Publishing Monitors: 11
Subscribing Monitors: 11
---
Traceback (most recent call last):
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 53, in _callback
    self._user_callback()
  File "./host_profiler.py", line 113, in _publish_profile
    self._host_monitor.start()
  File "./host_profiler.py", line 224, in start
    self._interval_timer.start()
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 30, in start
    return self._start()
  File "/home/dan/Source/rqt_graphprofiler/scripts/callback_timer.py", line 38, in _start
    raise RuntimeError("Timer thread already started.")
RuntimeError: Timer thread already started.
Updating Graph
Updating Graph
Updating Graph
Updating Graph
```

**Comment by mrdanbrooks** [comment]
functionality moved to rosprofiler
